version: 0.2
phases:
  pre_build:
    commands:
    - echo In the pre_build phase...
    - sudo apt-get -y install maven
  build:
    commands:
    - echo Build started on `date`
    - mvn install
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - '**/*'
